### ISSUE TITLE
Adjust About Menu Icon When Open

### ISSUE THREAD

**Issue by theryankelly** [MAPC/trailmap3#12]
About menu icon should be integrated when expanding the accordion.  Currently it remains floating next to accordion. I expect it to integrate with menu and provide option to close.  May need to design a new experience something like: https://cdn.dribbble.com/users/495792/screenshots/2293621/draft_02_dark_skin_light_orange.gif

Current:
![image](https://user-images.githubusercontent.com/2421382/63963785-c0feae00-ca63-11e9-8a64-a0268e3f97ad.png)

**Comment by dloutzenheiser** [comment]
The other example that you show makes sense.

**Comment by theryankelly** [comment]
https://www.massbuilds.com/map is another good example of how this could function.

**Comment by atomtay** [comment]
I added a temporary adjustment in commit [747f094](https://github.com/MAPC/trailmap3/commit/747f09445784d6b477e87e6e9c6608fef16d3e86) so that the toggle stays in place and the menu opens below:

![Screen Shot 2019-10-15 at 1 34 19 PM](https://user-images.githubusercontent.com/10645500/66855044-7fad5980-ef50-11e9-9a12-b7f9a2e35d10.png)

**Comment by theryankelly** [comment]
commit [747f094](https://github.com/MAPC/trailmap3/commit/747f09445784d6b477e87e6e9c6608fef16d3e86) resolves this issue.
