### ISSUE TITLE
Add Map Title and Header and Logos

### ISSUE THREAD

**Issue by dloutzenheiser** [MAPC/trailmap3#14]
A title of the page and MAPC logo needs to be added.  Title should should say something to the effect of "Trailmap: Metro Boston's Regional Walking and Cycling Map"

Example in Portland with the title in the top header (I don't like the pop up disclaimer though)
http://gis.oregonmetro.gov/historic_photo_viewer/#17/45.52776/-122.67667

**Comment by dloutzenheiser** [comment]
another example
https://www.dvrpc.org/webmaps/thecircuit/

**Comment by atomtay** [comment]
To clarify: in the most recent XD I could find (August 12), there's the MAPC and LandLine logos in the bottom left corner of the screen. Would a header with one (or both) logos be in addition to, or in lieu of, that footer?

**Comment by atomtay** [comment]
![Screen Shot 2019-09-23 at 3 00 18 PM](https://user-images.githubusercontent.com/10645500/65454353-f4d6b480-de12-11e9-91bf-3b891203f591.png)
Quick design check here before I merge into develop; I based the header off what we have at mapc.org so that the map is slightly visible underneath. (I also grabbed the semi-transparent SVG directly from the MAPC homepage too---do you know where I might be able to grab a local copy for this repo, @theryankelly ?)

**Comment by atomtay** [comment]
Resolved in commit [e25852a](https://github.com/MAPC/trailmap3/commit/e25852a9caf6bda5ce14f57d51e779f19b6e1ec6)
